GraphSandbox.Web/Models/CalendarEventModel.cs
namespace GraphSandbox.Web.Models
{
    public class CalendarEventModel
    {
        public string Id { set; get; }

        public string Title { set; get; }

        public DateTime? StartDateTime { set; get; }

        public DateTime? EndDateTime { set; get; }

        public string TimeZone { set; get; }
    }
}

GraphSandbox.Web/Models/CalendarModel.cs
namespace GraphSandbox.Web.Models
{
    public class CalendarModel
    {
        public List<CalendarEventModel> Events { get; set; }

        public CalendarEventModel TargetEvent { set; get; }
    }
}

GraphSandbox.Web/Models/ProfileModel.cs
namespace GraphSandbox.Web.Models
{
    public class ProfileModel
    {
        public string FirstName { set; get; }

        public string LastName { set; get; }

        public string Email { set; get; }

        public string PhotoData { set; get; }
    }
}

GraphSandbox.Web/Models/ToDoItemModel.cs
namespace GraphSandbox.Web.Models
{
    public class ToDoItemModel
    {
        public string Id { set; get; }

        public string Title { set; get; }

        public bool Completed { set; get; }
    }
}

GraphSandbox.Web/Models/ToDoModel.cs
namespace GraphSandbox.Web.Models
{
    public class ToDoModel
    {
        public Dictionary<string, string> TaskLists { get; set; }

        public string SelectedTaskListID { set; get; }

        public List<ToDoItemModel> Tasks { set; get; }

        public string ToDoItem { set; get; }
    }
}

GraphSandbox.Web/Controllers/CalendarController.cs
using GraphSandbox.Web.Models;
using GraphSandbox.Web.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;

namespace GraphSandbox.Web.Controllers
{
    public class CalendarController : Controller
    {
        private readonly ICalendarService _service;

        public CalendarController(ICalendarService service)
        {
            _service = service;
        }

        [AuthorizeForScopes(Scopes = ["calendars.readwrite"])]
        public async Task<IActionResult> Index(string? id)
        {
            var model = await _service.LoadCalendarEvents(id);
            return View(model);
        }

        [HttpPost]
        [AuthorizeForScopes(Scopes = ["calendars.readwrite"])]
        public async Task<IActionResult> Index(CalendarModel model)
        {
            ModelState.Clear();
            model = await _service.SaveCalendarEvent(model);
            return View(model);
        }

        [HttpPost]
        [AuthorizeForScopes(Scopes = ["calendars.readwrite"])]
        public IActionResult DeleteEvent(string id)
        {
            _service.DeleteCalendarEvent(id);
            return Ok();
        }
    }
}

GraphSandbox.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace GraphSandbox.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var user = HttpContext.User;
            
            return View();
        }
    }
}

GraphSandbox.Web/Controllers/ProfileController.cs
using GraphSandbox.Web.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;

namespace GraphSandbox.Web.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IProfileService _profileService;

        public ProfileController(IProfileService profileService)
        {
            _profileService = profileService;
        }

        [AuthorizeForScopes(Scopes = ["user.read"])]
        public async Task<IActionResult> Index()
        {
            var model = await _profileService.LoadProfile();
            return View(model);
        }
    }
}

GraphSandbox.Web/Controllers/ToDoController.cs
using GraphSandbox.Web.Models;
using GraphSandbox.Web.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;

namespace GraphSandbox.Web.Controllers
{
    public class ToDoController : Controller
    {
        private readonly IToDoService _service;

        public ToDoController(IToDoService service)
        {
            _service = service;
        }

        [AuthorizeForScopes(Scopes = ["tasks.readwrite"])]
        public async Task<IActionResult> Index(string? id)
        {
            var model = await _service.LoadTaskLists(id);
            return View(model);
        }

        [HttpPost]
        [AuthorizeForScopes(Scopes = ["tasks.readwrite"])]
        public async Task<IActionResult> Index(ToDoModel model)
        {
            ModelState.Clear();
            model = await _service.CreateTask(model);
            model.ToDoItem = string.Empty;
            return View(model);
        }

        [HttpPost]
        [AuthorizeForScopes(Scopes = ["tasks.readwrite"])]
        public IActionResult UpdateTaskStatus(string taskListID, string taskID, bool complete)
        {
            _service.UpdateTaskStatus(taskListID, taskID, complete);
            return Ok();
        }
    }
}

GraphSandbox.Web/Views/Calendar/Index.cshtml
@model GraphSandbox.Web.Models.CalendarModel
@{
    ViewData["Title"] = "Calendar Events";
}

@using (Html.BeginForm("Index", "Calendar", null, FormMethod.Post))
{
    <div class="row mt-5 justify-content-center">
        <div class="col-4">
            <div class="mb-1">
                <span class="form-label">Upcoming Events</span>
            </div>
            <ul class="list-group">
                @if (Model.Events != null)
                {
                    foreach (var item in Model.Events)
                    {
                        var active = !string.IsNullOrWhiteSpace(Model.TargetEvent.Id) && Model.TargetEvent.Id == item.Id;
                        var linkTitle = $"{item.Title} ({item.StartDateTime.Value.ToString("MMM, d")})";
                        @Html.ActionLink(linkTitle, "Index", "Calendar", new { id = item.Id }, new { @class = "list-group-item list-group-item-action " + (active ? "active" : "") })
                    }
                }
            </ul>
        </div>
        <div class="col-4">
            <div class="mb-3">
                <span class="form-label">Event Title</span>
                @Html.TextBoxFor(m => m.TargetEvent.Title, new { @class = "form-control" })
            </div>

            <div class="mb-3">
                <span class="form-label">Start Date</span>
                @Html.TextBoxFor(m => m.TargetEvent.StartDateTime, new { @class = "form-control" })
            </div>

            <div class="mb-3">
                <span class="form-label">End Date</span>
                @Html.TextBoxFor(m => m.TargetEvent.EndDateTime, new { @class = "form-control" })
            </div>

            @Html.HiddenFor(m => m.TargetEvent.Id)
            <input type="submit" class="btn btn-primary" value="@(string.IsNullOrWhiteSpace(Model.TargetEvent.Id) ? "Add" : "Save")" />

            @if (!string.IsNullOrWhiteSpace(Model.TargetEvent.Id))
            {
                <input type="button" class="btn btn-danger" value="Delete" onclick="deleteEvent('@Model.TargetEvent.Id')" />
            }

            @Html.ActionLink("Clear", "Index", "Calendar", new { id = string.Empty }, new { id="resetForm", @class = "btn btn-secondary" })
        </div>
    </div>
}

<script>
    function deleteEvent(id) {

        $.post(
            '/Calendar/DeleteEvent',
            {
                id
            },
            function (data, status) {
                console.log(status);
            }
        );

        return false;
    }
</script>

GraphSandbox.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4 mt-5">Welcome</h1>
    <p>This little web application is playground where I experiment with the Microsoft Graph SDK.</p>
</div>

GraphSandbox.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Graph Sandbox</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GraphSandbox.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Graph Sandbox</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">ToDo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GraphSandbox.Web/Views/ToDo/Index.cshtml
@model GraphSandbox.Web.Models.ToDoModel
@{
    ViewData["Title"] = "To Do";
}

@using (Html.BeginForm("Index", "ToDo", null, FormMethod.Post))
{
    <div class="row mt-5 justify-content-center">
        <div class="col-4">
            <ul class="list-group">
                @foreach (var item in Model.TaskLists)
                {
                    var active = !string.IsNullOrWhiteSpace(Model.SelectedTaskListID) && Model.SelectedTaskListID == item.Key;
                    @Html.ActionLink(item.Value, "Index", "ToDo", new { id = item.Key }, new { @class = "list-group-item list-group-item-action " + (active ? "active" : "") })
                }
            </ul>
        </div>
        <div class="col-4">
            @if (Model.Tasks != null)
            {
                @foreach (var item in Model.Tasks.OrderBy(x => x.Completed))
                {
                    <div class="input-group mb-3">
                        <div class="input-group-text">
                            @if (item.Completed)
                            {
                                <input class="form-check-input mt-0" type="checkbox" value="" checked onchange="updateTaskStatus('@Model.SelectedTaskListID', '@item.Id', this)">
                            }
                            else
                            {
                                <input class="form-check-input mt-0" type="checkbox" value="" onchange="updateTaskStatus('@Model.SelectedTaskListID', '@item.Id', this)">
                            }

                        </div>
                        <input type="text" class="form-control" value="@item.Title" readonly>
                    </div>
                }
                
                <div class="input-group">
                    @Html.HiddenFor(m => m.SelectedTaskListID)
                    @Html.TextBoxFor(m => m.ToDoItem, new { @class = "form-control", placeholder="New Task..." })
                    <input type="submit" class="btn btn-primary" value="Add" />
                </div>
            }
        </div>
    </div>
}

<script>
    function updateTaskStatus(taskListID, taskID, el) {
        var complete = $(el).is(':checked');

        $.post(
            '/ToDo/UpdateTaskStatus',
            {
                taskListID,
                taskID,
                complete
            },
            function (data, status) {
                console.log(status);
            }
        );
    }
</script>